# Generated by Django 5.2.15 on 2026-07-08 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
