# Generated by Django 5.2.15 on 2026-07-08 14:43

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('applicants', models.PositiveIntegerField(default=0)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='authentication.organization')),
            ],
            options={
                'ordering': ['-posted_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(default=datetime.date.today, editable=False)),
                ('program_name', models.CharField(max_length=255)),
                ('audience', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('approved', 'Approved'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_programs', to='authentication.organization')),
            ],
            options={
                'ordering': ['program_name'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(default=datetime.date.today, editable=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('last_working_day', models.DateField()),
                ('owner', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('approved', 'Approved'), ('closed', 'Closed'), ('archived', 'Archived')], default='pending', max_length=32)),
                ('assets_cleared', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_plans', to='authentication.organization')),
            ],
            options={
                'ordering': ['last_working_day', 'employee_name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(default=datetime.date.today, editable=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('owner', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('approved', 'Approved'), ('closed', 'Closed'), ('archived', 'Archived')], default='pending', max_length=32)),
                ('equipment_ready', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_plans', to='authentication.organization')),
            ],
            options={
                'ordering': ['start_date', 'employee_name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(default=datetime.date.today, editable=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('review_cycle', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('approved', 'Approved'), ('closed', 'Closed'), ('archived', 'Archived')], default='pending', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='authentication.organization')),
            ],
            options={
                'ordering': ['employee_name', 'review_cycle'],
            },
        ),
    ]
