# Generated by Django 5.2.15 on 2026-07-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_department_record_employee_manager_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='self_edits_period',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='employee',
            name='self_edits_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
