# Generated by Django 5.2.10 on 2026-07-12 21:25

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_userprofile_employee_userprofile_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(default=datetime.date.today, editable=False)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('headquarters_address', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('standard_check_in', models.TimeField(default=datetime.time(9, 0))),
                ('standard_check_out', models.TimeField(default=datetime.time(17, 0))),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('late_threshold_minutes', models.PositiveIntegerField(default=30)),
                ('auto_check_out', models.BooleanField(default=False)),
                ('work_days', models.JSONField(default=list)),
                ('two_factor_required', models.BooleanField(default=False)),
                ('password_expiry_days', models.PositiveIntegerField(default=90)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('enforce_single_session', models.BooleanField(default=False)),
                ('allowed_email_domain', models.CharField(blank=True, max_length=255)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_settings', to='authentication.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
