# Generated by Django 5.2.17 on 2026-08-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_settings', '0002_workspacesettings_icon_logo_workspacesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesettings',
            name='copilot_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
