# Generated by Django 5.2.15 on 2026-07-21 20:56

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_employee_userprofile_must_change_password'),
        ('employees', '0004_employee_self_edits_period_employee_self_edits_used'),
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(default=datetime.date.today, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('General', 'General'), ('Leave', 'Leave'), ('Attendance', 'Attendance'), ('Payroll', 'Payroll')], default='General', max_length=32)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_notifications', to='authentication.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'recipient', 'read_at'], name='platform_no_organiz_4de4b5_idx')],
            },
        ),
    ]
