# Generated by Django 5.2.17 on 2026-08-12 19:37

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_organization_status_organization_suspended_at_and_more'),
        ('departments', '0002_department_color'),
        ('employees', '0005_employee_deleted_at_employee_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(default=datetime.date.today, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_folders', to='authentication.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file_management.folder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(default=datetime.date.today, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('storage_bucket', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=1024)),
                ('content_type', models.CharField(blank=True, max_length=150)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('organization', 'Organization'), ('public', 'Public')], default='private', max_length=16)),
                ('default_access', models.CharField(choices=[('view', 'View only'), ('download', 'View and download')], default='download', max_length=16)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='authentication.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file_management.folder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='S3Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(default=datetime.date.today, editable=False)),
                ('bucket_name', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('endpoint_url', models.URLField(blank=True, max_length=500)),
                ('access_key_id', models.CharField(blank=True, max_length=255)),
                ('secret_access_key_encrypted', models.TextField(blank=True)),
                ('default_visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='s3_configuration', to='authentication.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(default=datetime.date.today, editable=False)),
                ('access_level', models.CharField(choices=[('view', 'View only'), ('download', 'View and download'), ('manage', 'Manage')], default='view', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_shares', to='departments.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_shares', to='employees.employee')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='file_management.fileasset')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', True), ('employee__isnull', False)), models.Q(('department__isnull', False), ('employee__isnull', True)), _connector='OR'), name='file_share_exactly_one_grantee'), models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('file', 'employee'), name='unique_file_share_per_employee'), models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('file', 'department'), name='unique_file_share_per_department')],
            },
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('organization', 'parent', 'name'), name='unique_folder_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['organization', 'folder', 'is_deleted'], name='file_manage_organiz_b7a73d_idx'),
        ),
    ]
