# Generated by Django 5.2.17 on 2026-08-13 08:05

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_color'),
        ('employees', '0005_employee_deleted_at_employee_is_deleted'),
        ('file_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('organization', 'Organization')], default='private', max_length=16),
        ),
        migrations.CreateModel(
            name='FolderShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(default=datetime.date.today, editable=False)),
                ('access_level', models.CharField(choices=[('view', 'View only'), ('manage', 'Manage')], default='view', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_shares', to='departments.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_shares', to='employees.employee')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='file_management.folder')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', True), ('employee__isnull', False)), models.Q(('department__isnull', False), ('employee__isnull', True)), _connector='OR'), name='folder_share_exactly_one_grantee'), models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('folder', 'employee'), name='unique_folder_share_per_employee'), models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('folder', 'department'), name='unique_folder_share_per_department')],
            },
        ),
    ]
